=== slrmoon/j2me-funkey-rgnano/phoneme-funkey-clean/phoneME-GP2X-SDL/phoneme_feature/jsr184/src/config/configuration.dtd
<!ELEMENT configuration (properties | constants | localized_strings | skin | rawimage)*>
<!ELEMENT properties (property)+>
<!ELEMENT property EMPTY>
<!ATTLIST property
        Key      CDATA                          #REQUIRED
        Value    CDATA                          #REQUIRED
        Scope    (system | internal)            "internal"
        Callout  CDATA                          #IMPLIED
        Comment  CDATA                          #IMPLIED
>

<!ELEMENT localized_strings (localized_string)*>
<!ATTLIST localized_strings
    Package     CDATA                           #REQUIRED
    Name        CDATA                           #REQUIRED
    KeysClass   CDATA                           #REQUIRED
    Scope       (protected | public)            "public"
    Comment     CDATA                           #IMPLIED
>
<!ELEMENT localized_string EMPTY>
<!ATTLIST localized_string
        Key         CDATA                   #REQUIRED
        KeyValue    CDATA                   #IMPLIED
        Value       CDATA                   #REQUIRED
>

<!ELEMENT constants (constant_class)*>
<!ELEMENT constant_class (constant)*>
<!ATTLIST constant_class
    Package  CDATA                          #REQUIRED
    Name     CDATA                          #REQUIRED
    Scope    (protected | public)           "public"
    Comment  CDATA                          #IMPLIED
    KeysValuesProvider (true | false)       "false"
    AutoValue  (true | false)               "false"
    JavaOnly   (true | false)               "false"
    NativeOnly (true | false)               "false"
>

=== slrmoon/j2me-funkey-rgnano/phoneme-funkey-clean/phoneME-GP2X-SDL/phoneme_feature/midp/src/configuration/configuration_xml/sdl/properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../share/configuration.dtd">
<!--
			

		Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
		DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
		
		This program is free software; you can redistribute it and/or
		modify it under the terms of the GNU General Public License version
		2 only, as published by the Free Software Foundation.
		
		This program is distributed in the hope that it will be useful, but
		WITHOUT ANY WARRANTY; without even the implied warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
		General Public License version 2 for more details (a copy is
		included at /legal/license.txt).
		
		You should have received a copy of the GNU General Public License
		version 2 along with this work; if not, write to the Free Software
		Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
		02110-1301 USA
		
		Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
		Clara, CA 95054 or visit www.sun.com if you need additional
		information or have any questions.
-->
<!-- THIS IS THE PROPERTIES FILE FOR SHARP ZAURUS 5500D ONLY!
	 YOU MAY NEED TO ADJUST THAT TO YOUR PLATFORM -->
<configuration>
<properties>
<!-- INTERNAL PROPERTIES -->
<!-- Visible from Configuration.getProperty() -->
  <!-- System tunable parameters -->

  <!-- Default values for SMS internal implementation -->
  <property Key="com.sun.midp.io.j2me.sms.Impl" 
		Value="com.sun.midp.io.j2me.sms.DatagramImpl" 
		Scope="internal"
		Comment="Select the low level transport handler."/>
  <property Key="com.sun.midp.io.j2me.sms.DatagramHost" 
		Value="smsdatagramhost"
		Comment="The datagram host name."/>
  <property Key="com.sun.midp.io.j2me.sms.DatagramPortIn" 
		Value="54321" 
		Scope="internal"
		Comment="The datagram port number for inbound messages from the SMS emulator."/>
  <property Key="com.sun.midp.io.j2me.sms.DatagramPortOut" 
		Value="12345" 
		Scope="internal"
		Comment="The datagram port number of a SMS emulator."/>

  <!-- Alternate SMS port for CBS emulation -->
  <property Key="com.sun.midp.io.j2me.sms.CBSPort" 
		Value="24680" 
		Scope="internal"
		Comment="Create a CBS message connection protocol port number"/>

  <!-- Sender's phone number -->
  <property Key="com.sun.midp.io.j2me.sms.PhoneNumber" 
		Value="+5551212" 
		Scope="internal"
		Comment="The phone number for outbound messages from the SMS emulator."/>

  <!-- Default SMS Service Center address -->
  <property Key="wireless.messaging.sms.smsc" 
		Value="+17815511212" 
		Scope="internal"
		Comment="Default SMS Service Center address."/>
  <property Key="VmDebuggerPort"
		Value="2808"
		Scope="internal"
		Comment="Default SMS Service Center address port number."/>

<!-- SYSTEM PROPERTIES -->
<!-- Visible from System.getProperty() -->

  <property Key="microedition.media.version"
		Value="1.1"
		Scope="system"
		Comment="MMAPI version number."/>
  <property Key="supports.mixing"
		Value="true"
		Scope="system"
		Comment="Audio mixing support."/>
  <property Key="supports.audio.capture"
		Value="false"
		Scope="system"
		Comment="Audio capture support."/>
  <property Key="supports.video.capture"
		Value="false"
		Scope="system"
		Comment="Video capture support."/>
  <property Key="supports.recording"
		Value="false"
		Scope="system"
		Comment="Media recording support."/>
  <property Key="audio.encodings"
		Value="encoding=midi encoding=wav encoding=amr"
		Scope="system"
		Comment="Supported audio playback encodings."/>
  <property Key="video.encodings"
		Value=""
		Scope="system"
		Comment="Supported video playback encodings."/>
  <property Key="video.snapshot.encodings"
		Value=""
		Scope="system"
		Comment="Supported video snapshot encodings."/>
  <property Key="streamable.contents"
		Value="audio/midi audio/x-midi audio/mid audio/x-mid audio/sp-midi audio/wav audio/x-wav audio/amr audio/amr-nb audio/x-tone-seq"
		Scope="system"
		Comment="Streamable media content types."/>
</properties>
</configuration>
